
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author project
 */
public class ScaleDrivers extends javax.swing.JFrame {
   JFrame frame=new JFrame();
    
       Connection con=null;
ResultSet re=null;
PreparedStatement pst =null;
    /*
     * Creates new form ScaleDrivers
     */
    public ScaleDrivers() {
        initComponents();
      frame.setTitle("Estimation Softwer Tool");
        con =sql_estool.ConnectDB();
      prn.setSelected(true);
      fln.setSelected(true);
      resln.setSelected(true);
      teamn.setSelected(true);
      pmatn.setSelected(true);
    }
public void close(){
        WindowEvent winColsingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winColsingEvent);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Back3 = new javax.swing.JButton();
        Next3 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanleprec = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        prn = new javax.swing.JRadioButton();
        prl = new javax.swing.JRadioButton();
        prvl = new javax.swing.JRadioButton();
        prh = new javax.swing.JRadioButton();
        prvh = new javax.swing.JRadioButton();
        jPanleflex = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        flvh = new javax.swing.JRadioButton();
        flh = new javax.swing.JRadioButton();
        flvl = new javax.swing.JRadioButton();
        fll = new javax.swing.JRadioButton();
        fln = new javax.swing.JRadioButton();
        jPanleresl = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        reslvh = new javax.swing.JRadioButton();
        reslh = new javax.swing.JRadioButton();
        resln = new javax.swing.JRadioButton();
        resll = new javax.swing.JRadioButton();
        reslvl = new javax.swing.JRadioButton();
        jPanelteam = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        teamvh = new javax.swing.JRadioButton();
        teamh = new javax.swing.JRadioButton();
        teamn = new javax.swing.JRadioButton();
        teaml = new javax.swing.JRadioButton();
        teamvl = new javax.swing.JRadioButton();
        jPanelpmat = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        pmatvh = new javax.swing.JRadioButton();
        pmath = new javax.swing.JRadioButton();
        pmatn = new javax.swing.JRadioButton();
        pmatl = new javax.swing.JRadioButton();
        pmatvl = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 450));
        setPreferredSize(new java.awt.Dimension(610, 412));
        setSize(new java.awt.Dimension(610, 412));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrblu.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 140, 440);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Back3.setBackground(new java.awt.Color(204, 204, 255));
        Back3.setText("Back");
        Back3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.SystemColor.activeCaption, java.awt.SystemColor.control));
        Back3.setPreferredSize(new java.awt.Dimension(90, 33));
        Back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back3ActionPerformed(evt);
            }
        });

        Next3.setBackground(new java.awt.Color(204, 204, 255));
        Next3.setText("Next");
        Next3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 255)));
        Next3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next3ActionPerformed(evt);
            }
        });
        Next3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Next3KeyPressed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(204, 204, 255));
        Exit.setText("Exit");
        Exit.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 255)));
        Exit.setPreferredSize(new java.awt.Dimension(90, 33));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Back3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Next3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Next3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(140, 330, 470, 110);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N

        jPanleprec.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel2.setText("1- PREC-- Precedentedness  ");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel3.setText("Is the new project comparable to projects your team has done ? ");

        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        buttonGroup1.add(prn);
        prn.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        prn.setText("Nominal");
        prn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prnActionPerformed(evt);
            }
        });

        buttonGroup1.add(prl);
        prl.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        prl.setText("Low");
        prl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prlActionPerformed(evt);
            }
        });

        buttonGroup1.add(prvl);
        prvl.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        prvl.setText("Very Low");
        prvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prvlActionPerformed(evt);
            }
        });

        buttonGroup1.add(prh);
        prh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        prh.setText("High");
        prh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prhActionPerformed(evt);
            }
        });

        buttonGroup1.add(prvh);
        prvh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        prvh.setText("Very High");
        prvh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prvhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prvl)
                    .addComponent(prvh)
                    .addComponent(prn)
                    .addComponent(prh)
                    .addComponent(prl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prvh)
                .addGap(18, 18, 18)
                .addComponent(prh)
                .addGap(18, 18, 18)
                .addComponent(prn)
                .addGap(18, 18, 18)
                .addComponent(prl)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(prvl)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanleprecLayout = new javax.swing.GroupLayout(jPanleprec);
        jPanleprec.setLayout(jPanleprecLayout);
        jPanleprecLayout.setHorizontalGroup(
            jPanleprecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleprecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanleprecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanleprecLayout.createSequentialGroup()
                        .addGroup(jPanleprecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanleprecLayout.setVerticalGroup(
            jPanleprecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleprecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" PREC", jPanleprec);

        jPanleflex.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 0, 11)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel16.setText("2- FLEX-- Development Flexibility");

        jLabel17.setFont(new java.awt.Font("Arial Unicode MS", 0, 14)); // NOI18N
        jLabel17.setText("Are your requirements flexible ?");

        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel11.setPreferredSize(new java.awt.Dimension(430, 233));

        buttonGroup2.add(flvh);
        flvh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        flvh.setText("Very High");
        flvh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flvhActionPerformed(evt);
            }
        });

        buttonGroup2.add(flh);
        flh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        flh.setText("High");
        flh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flhActionPerformed(evt);
            }
        });

        buttonGroup2.add(flvl);
        flvl.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        flvl.setText("Very Low");
        flvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flvlActionPerformed(evt);
            }
        });

        buttonGroup2.add(fll);
        fll.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        fll.setText("Low");

        buttonGroup2.add(fln);
        fln.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        fln.setText("Nominal");
        fln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(flvh)
                    .addComponent(fll)
                    .addComponent(fln)
                    .addComponent(flh)
                    .addComponent(flvl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flvh)
                .addGap(18, 18, 18)
                .addComponent(flh)
                .addGap(18, 18, 18)
                .addComponent(fln)
                .addGap(18, 18, 18)
                .addComponent(fll)
                .addGap(18, 18, 18)
                .addComponent(flvl)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanleflexLayout = new javax.swing.GroupLayout(jPanleflex);
        jPanleflex.setLayout(jPanleflexLayout);
        jPanleflexLayout.setHorizontalGroup(
            jPanleflexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleflexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanleflexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanleflexLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGroup(jPanleflexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanleflexLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(120, Short.MAX_VALUE))
                            .addGroup(jPanleflexLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanleflexLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap())
                    .addGroup(jPanleflexLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanleflexLayout.setVerticalGroup(
            jPanleflexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanleflexLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGroup(jPanleflexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanleflexLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel9))
                    .addGroup(jPanleflexLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("FLEX", jPanleflex);

        jPanleresl.setBackground(new java.awt.Color(204, 204, 255));

        jLabel18.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel18.setText("3- RESL-- Architecture / Risk Resolution");

        jLabel19.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel19.setText("To what degree have you already defined the architecture ?");

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setPreferredSize(new java.awt.Dimension(430, 233));

        buttonGroup3.add(reslvh);
        reslvh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        reslvh.setText("Very High");

        buttonGroup3.add(reslh);
        reslh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        reslh.setText("High");

        buttonGroup3.add(resln);
        resln.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        resln.setText("Nominal");

        buttonGroup3.add(resll);
        resll.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        resll.setText("Low");

        buttonGroup3.add(reslvl);
        reslvl.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        reslvl.setText("Very Low");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reslvl)
                    .addComponent(resll)
                    .addComponent(resln)
                    .addComponent(reslh)
                    .addComponent(reslvh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reslvh)
                .addGap(18, 18, 18)
                .addComponent(reslh)
                .addGap(18, 18, 18)
                .addComponent(resln)
                .addGap(18, 18, 18)
                .addComponent(resll)
                .addGap(18, 18, 18)
                .addComponent(reslvl)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanlereslLayout = new javax.swing.GroupLayout(jPanleresl);
        jPanleresl.setLayout(jPanlereslLayout);
        jPanlereslLayout.setHorizontalGroup(
            jPanlereslLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanlereslLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanlereslLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addGroup(jPanlereslLayout.createSequentialGroup()
                        .addGroup(jPanlereslLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanlereslLayout.setVerticalGroup(
            jPanlereslLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanlereslLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RESL", jPanleresl);

        jPanelteam.setBackground(new java.awt.Color(204, 204, 255));

        jLabel12.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel12.setText("4- TEAM-- Team Cohesion");

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel13.setText("How you describe the relationships among the stakeholders ?");

        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel10.setMinimumSize(new java.awt.Dimension(430, 233));

        buttonGroup4.add(teamvh);
        teamvh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        teamvh.setText("Very High");

        buttonGroup4.add(teamh);
        teamh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        teamh.setText("High");

        buttonGroup4.add(teamn);
        teamn.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        teamn.setText("Nominal");

        buttonGroup4.add(teaml);
        teaml.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        teaml.setText("Low");

        buttonGroup4.add(teamvl);
        teamvl.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        teamvl.setText("Very Low");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamvh)
                    .addComponent(teaml)
                    .addComponent(teamn)
                    .addComponent(teamh)
                    .addComponent(teamvl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamvh)
                .addGap(18, 18, 18)
                .addComponent(teamh)
                .addGap(18, 18, 18)
                .addComponent(teamn)
                .addGap(18, 18, 18)
                .addComponent(teaml)
                .addGap(18, 18, 18)
                .addComponent(teamvl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelteamLayout = new javax.swing.GroupLayout(jPanelteam);
        jPanelteam.setLayout(jPanelteamLayout);
        jPanelteamLayout.setHorizontalGroup(
            jPanelteamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelteamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelteamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelteamLayout.createSequentialGroup()
                        .addGroup(jPanelteamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelteamLayout.setVerticalGroup(
            jPanelteamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelteamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TEAM", jPanelteam);

        jPanelpmat.setBackground(new java.awt.Color(204, 204, 255));

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 1, 12)); // NOI18N
        jLabel14.setText("5- PMAT-- Process maturity ");

        jLabel15.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel15.setText("How does your organization rate ? ");

        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        buttonGroup5.add(pmatvh);
        pmatvh.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        pmatvh.setText("Very High");

        buttonGroup5.add(pmath);
        pmath.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        pmath.setText("High");

        buttonGroup5.add(pmatn);
        pmatn.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        pmatn.setText("Nominal");

        buttonGroup5.add(pmatl);
        pmatl.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        pmatl.setText("Low");
        pmatl.setActionCommand("pmatl");

        buttonGroup5.add(pmatvl);
        pmatvl.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        pmatvl.setText("Very Low");
        pmatvl.setActionCommand("pmatvl");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pmatvl)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pmatvh)
                        .addComponent(pmatn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pmath, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pmatl, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pmatvh)
                .addGap(18, 18, 18)
                .addComponent(pmath)
                .addGap(18, 18, 18)
                .addComponent(pmatn)
                .addGap(18, 18, 18)
                .addComponent(pmatl)
                .addGap(18, 18, 18)
                .addComponent(pmatvl)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelpmatLayout = new javax.swing.GroupLayout(jPanelpmat);
        jPanelpmat.setLayout(jPanelpmatLayout);
        jPanelpmatLayout.setHorizontalGroup(
            jPanelpmatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelpmatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelpmatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelpmatLayout.createSequentialGroup()
                        .addGroup(jPanelpmatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 249, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelpmatLayout.setVerticalGroup(
            jPanelpmatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelpmatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PMAT", jPanelpmat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(140, 0, 470, 330);

        setBounds(150, 100, 631, 483);
    }// </editor-fold>//GEN-END:initComponents

    

    private void Back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back3ActionPerformed
    
        Size size = new Size();
close(); 
size.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_Back3ActionPerformed

    private void Next3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next3ActionPerformed
 try {
    
     
  ScaleDrivers scaledr=new ScaleDrivers();
         Size si=new Size(); 
     
  
    double sxaldr=0;
 double prec=0; 
double flex=0;
double resl=0;
double team=0;
double pmat=0;


//1- PREC-- Precedentedness
        if(prn.isSelected()){
        prec=3.72  ;
    }
    if (prl.isSelected()){
       prec=4.96 ;
    }else
     if (prh.isSelected()){
       prec=2.48 ;
     }
      if (prvh.isSelected()){
       prec=1.24;
      }
     
       if (prvl.isSelected()) {
       prec=6.20 ;
       }
//2- FLEX-- Development Flexibility
if(fln.isSelected()){
       flex=3.04 ;
    }
    if (fll.isSelected()){
       flex=4.05 ;
    }
     if (flvl.isSelected()){
       flex=5.07 ;
     }
      if (flh.isSelected()){
       flex=2.03 ;
      }
     
       if (flvh.isSelected()) {
       flex=1.01;
       }
       //end
       //
       if(resln.isSelected()){
       resl=4.24 ;
    }
    if (resll.isSelected()){
       resl=5.65 ;
    }
     if (reslvl.isSelected()){
       resl=7.07;
     }
      if (reslh.isSelected()){
       resl=2.83 ;
      }
       if (reslvh.isSelected()) {
       resl=1.41;
       }
       //end
       //
           if(teamn.isSelected()){
       team=3.29;
    }
    if (teaml.isSelected()){
       team=4.38 ;
    }
     if (teamvl.isSelected()){
       team=5.48;
     }
      if (reslh.isSelected()){
       team=2.19 ;
      }
       if (teamvh.isSelected()) {
       team=1.10 ;
       }
       //end
       //
       
            if(pmatn.isSelected()){
       pmat=4.68 ;
    }
    if (pmatl.isSelected()){
       team=6.24;
    }
     if (pmatvl.isSelected()){
       pmat=7.80 ;
     }
      if (pmath.isSelected()){
       pmat=3.12;
      }
       if (pmatvh.isSelected()) {
       pmat=1.56;
       }
        
       sxaldr=(prec+flex+resl+team+pmat);
             
       String upsql="UPDATE estool set sdr='"+sxaldr+"' WHERE idnum=(select max(idnum) From estool)"; 
  pst=con.prepareStatement(upsql); 
pst.execute(); 
pst.close();

      
        CostDrivers cost = new CostDrivers();
close();
cost.setVisible(true);
 }
 catch(Exception e){
     JOptionPane.showMessageDialog(null, e);
 }
// TODO add your handling code here:
    }//GEN-LAST:event_Next3ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void flhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flhActionPerformed

    private void flvhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flvhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flvhActionPerformed

    private void prhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prhActionPerformed

    private void prnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prnActionPerformed

    private void prlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prlActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_prlActionPerformed

    private void prvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prvlActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_prvlActionPerformed

    private void prvhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prvhActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_prvhActionPerformed

    private void flnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flnActionPerformed

    private void flvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flvlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flvlActionPerformed

    private void Next3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Next3KeyPressed
       try {
    
     
  ScaleDrivers scaledr=new ScaleDrivers();
         Size si=new Size(); 
     
  
    double sxaldr=0;
 double prec=0; 
double flex=0;
double resl=0;
double team=0;
double pmat=0;


//1- PREC-- Precedentedness
        if(prn.isSelected()){
        prec=3.72  ;
    }
    if (prl.isSelected()){
       prec=4.96 ;
    }else
     if (prh.isSelected()){
       prec=2.48 ;
     }
      if (prvh.isSelected()){
       prec=1.24;
      }
     
       if (prvl.isSelected()) {
       prec=6.20 ;
       }
//2- FLEX-- Development Flexibility
if(fln.isSelected()){
       flex=3.04 ;
    }
    if (fll.isSelected()){
       flex=4.05 ;
    }
     if (flvl.isSelected()){
       flex=5.07 ;
     }
      if (flh.isSelected()){
       flex=2.03 ;
      }
     
       if (flvh.isSelected()) {
       flex=1.01;
       }
       //end
       //
       if(resln.isSelected()){
       resl=4.24 ;
    }
    if (resll.isSelected()){
       resl=5.65 ;
    }
     if (reslvl.isSelected()){
       resl=7.07;
     }
      if (reslh.isSelected()){
       resl=2.83 ;
      }
       if (reslvh.isSelected()) {
       resl=1.41;
       }
       //end
       //
           if(teamn.isSelected()){
       team=3.29;
    }
    if (teaml.isSelected()){
       team=4.38 ;
    }
     if (teamvl.isSelected()){
       team=5.48;
     }
      if (reslh.isSelected()){
       team=2.19 ;
      }
       if (teamvh.isSelected()) {
       team=1.10 ;
       }
       //end
       //
       
            if(pmatn.isSelected()){
       pmat=4.68 ;
    }
    if (pmatl.isSelected()){
       team=6.24;
    }
     if (pmatvl.isSelected()){
       pmat=7.80 ;
     }
      if (pmath.isSelected()){
       pmat=3.12;
      }
       if (pmatvh.isSelected()) {
       pmat=1.56;
       }
        
       sxaldr=(prec+flex+resl+team+pmat);
             
       String upsql="UPDATE estool set sdr='"+sxaldr+"' WHERE idnum=(select max(idnum) From estool)"; 
  pst=con.prepareStatement(upsql); 
pst.execute(); 
pst.close();

      
        CostDrivers cost = new CostDrivers();
close();
cost.setVisible(true);
 }
 catch(Exception e){
     JOptionPane.showMessageDialog(null, e);
 } // TODO add your handling code here:
    }//GEN-LAST:event_Next3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScaleDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScaleDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScaleDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScaleDrivers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ScaleDrivers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back3;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Next3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton flh;
    private javax.swing.JRadioButton fll;
    private javax.swing.JRadioButton fln;
    private javax.swing.JRadioButton flvh;
    private javax.swing.JRadioButton flvl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelpmat;
    private javax.swing.JPanel jPanelteam;
    private javax.swing.JPanel jPanleflex;
    private javax.swing.JPanel jPanleprec;
    private javax.swing.JPanel jPanleresl;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lab1;
    private javax.swing.JRadioButton pmath;
    private javax.swing.JRadioButton pmatl;
    private javax.swing.JRadioButton pmatn;
    private javax.swing.JRadioButton pmatvh;
    private javax.swing.JRadioButton pmatvl;
    private javax.swing.JRadioButton prh;
    private javax.swing.JRadioButton prl;
    private javax.swing.JRadioButton prn;
    private javax.swing.JRadioButton prvh;
    private javax.swing.JRadioButton prvl;
    private javax.swing.JRadioButton reslh;
    private javax.swing.JRadioButton resll;
    private javax.swing.JRadioButton resln;
    private javax.swing.JRadioButton reslvh;
    private javax.swing.JRadioButton reslvl;
    private javax.swing.JRadioButton teamh;
    private javax.swing.JRadioButton teaml;
    private javax.swing.JRadioButton teamn;
    private javax.swing.JRadioButton teamvh;
    private javax.swing.JRadioButton teamvl;
    // End of variables declaration//GEN-END:variables

}
